export enum ErrorCodes {
    // General Errors
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    NOT_FOUND = 'NOT_FOUND',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    CONFLICT = 'CONFLICT',
    BAD_REQUEST = 'BAD_REQUEST',
    UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
    TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

    // Authentication & Authorization Errors
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    TOKEN_INVALID = 'TOKEN_INVALID',
    TOKEN_MISSING = 'TOKEN_MISSING',
    REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
    INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
    INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',
    TWO_FACTOR_REQUIRED = 'TWO_FACTOR_REQUIRED',
    TWO_FACTOR_INVALID = 'TWO_FACTOR_INVALID',
    EMAIL_VERIFICATION_REQUIRED = 'EMAIL_VERIFICATION_REQUIRED',

    // User Account Errors
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    ACCOUNT_DEACTIVATED = 'ACCOUNT_DEACTIVATED',
    ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
    ACCOUNT_BLOCKED = 'ACCOUNT_BLOCKED',
    EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
    INVALID_EMAIL_VERIFICATION_TOKEN = 'INVALID_EMAIL_VERIFICATION_TOKEN',
    PASSWORD_RESET_TOKEN_INVALID = 'PASSWORD_RESET_TOKEN_INVALID',
    PASSWORD_RESET_TOKEN_EXPIRED = 'PASSWORD_RESET_TOKEN_EXPIRED',
    PASSWORD_RECENTLY_USED = 'PASSWORD_RECENTLY_USED',
    CURRENT_PASSWORD_INCORRECT = 'CURRENT_PASSWORD_INCORRECT',
    PASSWORD_CONFIRMATION_MISMATCH = 'PASSWORD_CONFIRMATION_MISMATCH',

    // Role & Permission Errors
    ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
    ROLE_ALREADY_EXISTS = 'ROLE_ALREADY_EXISTS',
    PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',
    DEFAULT_ROLE_NOT_FOUND = 'DEFAULT_ROLE_NOT_FOUND',

    // ASACI Service Errors
    ASACI_CONNECTION_ERROR = 'ASACI_CONNECTION_ERROR',
    ASACI_AUTHENTICATION_FAILED = 'ASACI_AUTHENTICATION_FAILED',
    ASACI_AUTHORIZATION_FAILED = 'ASACI_AUTHORIZATION_FAILED',
    ASACI_SERVICE_UNAVAILABLE = 'ASACI_SERVICE_UNAVAILABLE',
    ASACI_INVALID_RESPONSE = 'ASACI_INVALID_RESPONSE',
    ASACI_REQUEST_TIMEOUT = 'ASACI_REQUEST_TIMEOUT',
    ASACI_RATE_LIMIT_EXCEEDED = 'ASACI_RATE_LIMIT_EXCEEDED',
    ASACI_QUOTA_EXCEEDED = 'ASACI_QUOTA_EXCEEDED',

    // Certificate Errors
    CERTIFICATE_NOT_FOUND = 'CERTIFICATE_NOT_FOUND',
    CERTIFICATE_ALREADY_CANCELLED = 'CERTIFICATE_ALREADY_CANCELLED',
    CERTIFICATE_ALREADY_SUSPENDED = 'CERTIFICATE_ALREADY_SUSPENDED',
    CERTIFICATE_INVALID_STATUS = 'CERTIFICATE_INVALID_STATUS',
    CERTIFICATE_DOWNLOAD_FAILED = 'CERTIFICATE_DOWNLOAD_FAILED',

    // Order Errors
    ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
    ORDER_INVALID_STATUS = 'ORDER_INVALID_STATUS',
    ORDER_CANNOT_BE_MODIFIED = 'ORDER_CANNOT_BE_MODIFIED',
    ORDER_ALREADY_APPROVED = 'ORDER_ALREADY_APPROVED',
    ORDER_ALREADY_REJECTED = 'ORDER_ALREADY_REJECTED',
    ORDER_ALREADY_CANCELLED = 'ORDER_ALREADY_CANCELLED',
    ORDER_QUANTITY_INVALID = 'ORDER_QUANTITY_INVALID',

    // Transaction Errors
    TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
    TRANSACTION_INVALID_STATUS = 'TRANSACTION_INVALID_STATUS',
    TRANSACTION_CANNOT_BE_MODIFIED = 'TRANSACTION_CANNOT_BE_MODIFIED',
    TRANSACTION_ALREADY_APPROVED = 'TRANSACTION_ALREADY_APPROVED',
    TRANSACTION_ALREADY_REJECTED = 'TRANSACTION_ALREADY_REJECTED',
    TRANSACTION_INSUFFICIENT_BALANCE = 'TRANSACTION_INSUFFICIENT_BALANCE',

    // Production Errors
    PRODUCTION_NOT_FOUND = 'PRODUCTION_NOT_FOUND',
    PRODUCTION_INVALID_STATUS = 'PRODUCTION_INVALID_STATUS',
    PRODUCTION_DOWNLOAD_FAILED = 'PRODUCTION_DOWNLOAD_FAILED',
    PRODUCTION_INVALID_DATA = 'PRODUCTION_INVALID_DATA',

    // Organization & Office Errors
    ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
    ORGANIZATION_ALREADY_EXISTS = 'ORGANIZATION_ALREADY_EXISTS',
    ORGANIZATION_INACTIVE = 'ORGANIZATION_INACTIVE',
    OFFICE_NOT_FOUND = 'OFFICE_NOT_FOUND',
    OFFICE_ALREADY_EXISTS = 'OFFICE_ALREADY_EXISTS',
    OFFICE_INACTIVE = 'OFFICE_INACTIVE',

    // File & Upload Errors
    FILE_NOT_FOUND = 'FILE_NOT_FOUND',
    FILE_TOO_LARGE = 'FILE_TOO_LARGE',
    FILE_INVALID_TYPE = 'FILE_INVALID_TYPE',
    FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
    FILE_PROCESSING_FAILED = 'FILE_PROCESSING_FAILED',

    // Database Errors
    DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR',
    DATABASE_QUERY_ERROR = 'DATABASE_QUERY_ERROR',
    DATABASE_CONSTRAINT_VIOLATION = 'DATABASE_CONSTRAINT_VIOLATION',
    DATABASE_TIMEOUT = 'DATABASE_TIMEOUT',

    // External Service Errors
    EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
    EXTERNAL_SERVICE_TIMEOUT = 'EXTERNAL_SERVICE_TIMEOUT',
    EXTERNAL_SERVICE_UNAVAILABLE = 'EXTERNAL_SERVICE_UNAVAILABLE',

    // Configuration Errors
    CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
    CONFIGURATION_MISSING = 'CONFIGURATION_MISSING',
    CONFIGURATION_INVALID = 'CONFIGURATION_INVALID',

    // Business Logic Errors
    BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
    INVALID_OPERATION = 'INVALID_OPERATION',
    OPERATION_NOT_ALLOWED = 'OPERATION_NOT_ALLOWED',
    PRECONDITION_FAILED = 'PRECONDITION_FAILED',

    // Network & Communication Errors
    NETWORK_ERROR = 'NETWORK_ERROR',
    CONNECTION_TIMEOUT = 'CONNECTION_TIMEOUT',
    CONNECTION_REFUSED = 'CONNECTION_REFUSED',
    DNS_RESOLUTION_FAILED = 'DNS_RESOLUTION_FAILED',

    // Cache & Session Errors
    CACHE_ERROR = 'CACHE_ERROR',
    SESSION_EXPIRED = 'SESSION_EXPIRED',
    SESSION_INVALID = 'SESSION_INVALID',

    // Webhook & Integration Errors
    WEBHOOK_DELIVERY_FAILED = 'WEBHOOK_DELIVERY_FAILED',
    WEBHOOK_INVALID_SIGNATURE = 'WEBHOOK_INVALID_SIGNATURE',
    INTEGRATION_ERROR = 'INTEGRATION_ERROR',
    API_VERSION_UNSUPPORTED = 'API_VERSION_UNSUPPORTED'
}